[package]
name = "ufo_c"
version = "0.2.0"
authors = ["Colette ğŸŒ©ï¸â€ğŸ’ Kerr <Colette.m.y.Kerr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
crossbeam = "0.8.0" 
libc = "0.2.80"
stderrlog = "0.5.1"
ufo_core = { git = "https://github.com/ufo-org/ufo-core.git", features = ["parallel_hashing"] }
#ufo_core = { path = "/home/ckerr/workspace/ufo/ufo-core", features = ["parallel_hashing"] }


[lib]
name = "ufo_c"
crate-type = ["dylib", "staticlib"]

[build-dependencies]
cbindgen = "0.18.0"
stderrlog = "0.5.1"

[profile.release]
lto = true # better optimizations